//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCars.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RentCars.Exceptions.ResourceExceptionMessages", typeof(ResourceExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;address&apos; cannot be empty..
        /// </summary>
        public static string ADDRESS_EMPTY {
            get {
                return ResourceManager.GetString("ADDRESS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;birth_date&apos; cannot be empty..
        /// </summary>
        public static string BIRTH_DATE_USER_EMPTY {
            get {
                return ResourceManager.GetString("BIRTH_DATE_USER_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;brand&apos; cannot be empty..
        /// </summary>
        public static string BRAND_EMPTY {
            get {
                return ResourceManager.GetString("BRAND_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;city&apos; cannot be empty..
        /// </summary>
        public static string CITY_ADDRESS_EMPTY {
            get {
                return ResourceManager.GetString("CITY_ADDRESS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;country&apos; cannot be empty..
        /// </summary>
        public static string COUNTRY_ADDRESS_EMPTY {
            get {
                return ResourceManager.GetString("COUNTRY_ADDRESS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;ddd&apos; cannot be empty..
        /// </summary>
        public static string DDD_USER_EMPTY {
            get {
                return ResourceManager.GetString("DDD_USER_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;document_type&apos; cannot be empty..
        /// </summary>
        public static string DOCUMENT_TYPE_USER_EMPTY {
            get {
                return ResourceManager.GetString("DOCUMENT_TYPE_USER_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;document_type&apos; cannot be empty..
        /// </summary>
        public static string DOCUMENT_USER_EMPTY {
            get {
                return ResourceManager.GetString("DOCUMENT_USER_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;email&apos; cannot be empty..
        /// </summary>
        public static string EMAIL_USER_EMPTY {
            get {
                return ResourceManager.GetString("EMAIL_USER_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;gender&apos; cannot be empty..
        /// </summary>
        public static string GENDER_EMPTY {
            get {
                return ResourceManager.GetString("GENDER_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address provided is invalid..
        /// </summary>
        public static string INVALID_EMAIL_ADDRESS {
            get {
                return ResourceManager.GetString("INVALID_EMAIL_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;lastname&apos; cannot be empty..
        /// </summary>
        public static string LASTNAME_USER_EMPTY {
            get {
                return ResourceManager.GetString("LASTNAME_USER_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Plate already registered for another car..
        /// </summary>
        public static string LICENSE_PLATE_ALREADY_REGISTERED {
            get {
                return ResourceManager.GetString("LICENSE_PLATE_ALREADY_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;license_Plate&apos; cannot be empty..
        /// </summary>
        public static string LICENSE_PLATE_EMPTY {
            get {
                return ResourceManager.GetString("LICENSE_PLATE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;license plate&quot; should be between 0 and 7 characteres length..
        /// </summary>
        public static string LICENSE_PLATE_LENGTH_OUT_OF_RANGE {
            get {
                return ResourceManager.GetString("LICENSE_PLATE_LENGTH_OUT_OF_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;model&apos; cannot be empty..
        /// </summary>
        public static string MODEL_EMPTY {
            get {
                return ResourceManager.GetString("MODEL_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;name&apos; cannot be empty..
        /// </summary>
        public static string NAME_USER_EMPTY {
            get {
                return ResourceManager.GetString("NAME_USER_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;neighborhood&apos; cannot be empty..
        /// </summary>
        public static string NEIGHBORHOOD_ADDRESS_EMPTY {
            get {
                return ResourceManager.GetString("NEIGHBORHOOD_ADDRESS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;num_Passengers&apos; must be greater than zero..
        /// </summary>
        public static string NUM_PASSENGER_NOT_GREATER_THAN_ZERO {
            get {
                return ResourceManager.GetString("NUM_PASSENGER_NOT_GREATER_THAN_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;password&apos; cannot be empty..
        /// </summary>
        public static string PASSWORD_USER_EMPTY {
            get {
                return ResourceManager.GetString("PASSWORD_USER_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;phone&apos; cannot be empty..
        /// </summary>
        public static string PHONE_USER_EMPTY {
            get {
                return ResourceManager.GetString("PHONE_USER_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;state&apos; cannot be empty..
        /// </summary>
        public static string STATE_ADDRESS_EMPTY {
            get {
                return ResourceManager.GetString("STATE_ADDRESS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;steering_type&apos; cannot be empty and must be one of the values: &quot;mechanical&quot;, &quot;hydraulic&quot;, &quot;electric&quot; and  &quot;electroHydraulic&quot;..
        /// </summary>
        public static string STEERING_TYPE_INVALID {
            get {
                return ResourceManager.GetString("STEERING_TYPE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;street&apos; cannot be empty..
        /// </summary>
        public static string STREET_ADDRESS_EMPTY {
            get {
                return ResourceManager.GetString("STREET_ADDRESS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error occurred..
        /// </summary>
        public static string UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;year&apos; cannot be empty..
        /// </summary>
        public static string YEAR_EMPTY {
            get {
                return ResourceManager.GetString("YEAR_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;year&apos; field must be greater than 1908. It&apos;s unlikely that the car being registered is older than that..
        /// </summary>
        public static string YEAR_FIRST_FORD {
            get {
                return ResourceManager.GetString("YEAR_FIRST_FORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;zip_code&apos; cannot be empty..
        /// </summary>
        public static string ZIP_CODE_ADDRESS_EMPTY {
            get {
                return ResourceManager.GetString("ZIP_CODE_ADDRESS_EMPTY", resourceCulture);
            }
        }
    }
}
